### ISSUE TITLE
 Inquiry About Package Updates and Stability

### ISSUE THREAD

**Issue by jbarasa** [bdragon300/tusgo#1]
Hello,

I'm new to using the tusgo package and noticed that the last commit was last year. I wanted to ask if there are any plans for future updates or if the package is considered stable for ongoing use.

Thank you for your time!

**Comment by bdragon300** [comment]
Hello! Thanks for using tusgo.

This package supports all TUS protocol features, so there are no plans for releases other than bugfixes. I plan to issue a release just to bump dependencies versions this month or so.

**Comment by AhmedAbouelkher** [comment]
> Hello! Thanks for using tusgo.
> 
> This package supports all TUS protocol features, so there are no plans for releases other than bugfixes. I plan to issue a release just to bump dependencies versions this month or so.

it lack sending custom headers with the request. Are you using this package in production?

Most important, The package is very hard to use and implement without any clear reason for that.

**Comment by bdragon300** [comment]
Hello.

> it lack sending custom headers with the request

Which headers do you mean? If you want to construct a custom request with you own headers, you may use `GetRequest` callback in Client https://pkg.go.dev/github.com/bdragon300/tusgo#Client

> Most important, The package is very hard to use and implement without any clear reason for that.

This package is intended to be used with stdlib functions from `io`, `bufio` etc packages for more flexibility. What are you trying to do?

Thanks.
